package com.groupware.orca.document.mapper;

import com.groupware.orca.document.vo.DocumentVo;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface DocumentMapper {

    @Select("SELECT D.DOC_NO ,D.WRITER_NO ,D.STATUS ,D.TITLE ,D.CONTENT ,D.ENROLL_DATE ,D.CREDIT_DATE ,D.URGENT ,T.TITLE AS templateTitle ,TC.NAME AS categoryName ,AL.DOC_NO AS approvalDocNo ,AL.SEQ ,AL.APPROVAL_DATE ,AL.APPROVER_CLASSIFICATION_NO ,PI.NAME AS writerName ,DEPT.PARTNAME AS dept ,P.NAME_OF_POSITION AS position ,DRL.REFERRER_NO FROM DOCUMENT D JOIN DOC_TEMPLATE T ON D.TEMPLATE_NO = T.TEMPLATE_NO JOIN DOC_TEMPLATE_CATEGORY TC ON T.CATEGORY_NO = TC.CATEGORY_NO LEFT JOIN APPR_LINE AL ON D.DOC_NO = AL.DOC_NO LEFT JOIN PERSONNEL_INFORMATION PI ON AL.APPROVER_NO = PI.EMP_NO LEFT JOIN DOC_REFERENCE_LIST DRL ON DRL.REFERRER_NO = PI.EMP_NO LEFT JOIN DEPARTMENT DEPT ON DEPT.DEPT_CODE = AL.DEPT_CODE LEFT JOIN POSITION P ON P.POSITION_CODE = AL.POSITION_CODE WHERE D.DEL_YN = 'N' ORDER BY D.ENROLL_DATE DESC")
    List<DocumentVo> getDocumentList();
}
